### ISSUE TITLE
compatibility with some old version pythons.

### ISSUE THREAD

**Issue by Cissoid** [python-hyper/hyperframe#46]
Some old version pythons will raise exceptions when use struct.unpack with a memoryview object. In hyper 0.5.0 this exception was raised, and now there will raise a `InvalidFrameError `, but hyper is not available yet. 

Maybe this problem could be easily fixed, just convert memoryview to bytes use memoryview.tobytes()?

Here's my test results:

```
$ python
Python 2.7.2 (default, Dec  6 2011, 12:12:28)
[GCC 4.4.4 20100726 (Red Hat 4.4.4-13)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import struct
>>> struct.unpack('!4c', memoryview('abcd'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
struct.error: unpack requires a string argument of length 4
>>> struct.unpack('!4c', memoryview('abcd').tobytes())
('a', 'b', 'c', 'd')
```

```
$ python
Python 2.7.6 (default, Jun 22 2015, 18:00:18)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import struct
>>> struct.unpack('!4c', memoryview('abcd'))
('a', 'b', 'c', 'd')
>>> struct.unpack('!4c', memoryview('abcd').tobytes())
('a', 'b', 'c', 'd')
```

```
$ python3
Python 3.5.1 (default, Apr 18 2016, 11:46:32)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import struct
>>> struct.unpack('!4c', memoryview(b'abcd'))
(b'a', b'b', b'c', b'd')
>>> struct.unpack('!4c', memoryview(b'abcd').tobytes())
(b'a', b'b', b'c', b'd')
```

**Comment by Lukasa** [comment]
Yeah, I'm aware of this problem. =(

Converting memoryviews to bytes unconditionally is not really a great idea because it costs us performance on platforms that don't require it. However, I'm acutely aware that this is a problem on older Python versions such as the one you're using.

*With that said*, you'll find a lot of HTTP/2 problems with a Python version that old: in particular, you're likely to have a very old OpenSSL as well. While I'm open to pursuing ways of fixing this, are you potentially open to using a Python other than the one your distribution is providing, or asking your distribution to backport this specific fix?

**Comment by Cissoid** [comment]
You are right, we also have an old OpenSSL and this cause many other problems. But we run a large system using python 2.7.2 for several years, so update python or OpenSSL version may be a dangerous operation. 

Currently our solution is manual maintain a hyper and make patches for some you said "old OpenSSL problems", it's not a perfect way but works well. Thanks for your reply.
