### ISSUE TITLE
doesn't play well with python 2.7.9

### ISSUE THREAD

**Issue by jinghanx** [python-hyper/hyperframe#67]
Hey hyperframe folks,

I realized python 2 below 2.7.9 doesn't do well in SSL and wan't supported by hyper. 
But my code base is 2.7.3. So in order to use http2, I commented out tobytes() call in frame.py, and make the "data" param of parse_body function call pure string instead of memoryview obj. 
It seems to work for me, but I am wondering what is the bad thing about this hack.

**Comment by Lukasa** [comment]
@jinghanx There's nothing bad about this hack, but it shouldn't be necessary. The `memoryview` object moderately increases our speed because it means we can avoid copying data until we need to, which is convenient, but the `memoryview` in Python 2.7.3 doesn't support being passed to `struct`. That was fixed in Python 2.7.4, so I *strongly* recommend upgrading your Python rather than making this change.

**Comment by jinghanx** [comment]
Gotcha, thx for explaining.

**Comment by Lukasa** [comment]
No problem!
